server:
  port: 8080
  servlet:
    context-path: /


spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/customers/**,/api/carts/**
          filters:
            - name: AuthFilter
            - name: CircuitBreaker
              args:
                name: customer-service
                fallbackUri: forward:/fallback/customers
        - id: order-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/orders/**,/api/order-items/**,/api/payments/**
          filters:
            - name: AuthFilter
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackUri: forward:/fallback/orders
        - id: product-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/products/**,/api/categories/**,/api/reviews/**
          filters:
            - name: AuthFilter
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackUri: forward:/fallback/products
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth-service
                fallbackUri: forward:/fallback/auth


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: gateway-service
        primaryName: API Gateway Service
      - url: /product-service/v3/api-docs
        name: product-service
        primaryName: Product Service



management:
  tracing:
    sampling:
      probability: 1.0
