server:
  port: 8999

spring:
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mailUsername}
    password: ${mailPassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls: true

management:
  tracing:
    sampling:
      probability: 1.0

kafka:
  bootstrapAddress: localhost:9092
